### ISSUE TITLE
Tries to compile sass files from external component package

### ISSUE THREAD

**Issue by seanwuapps** [ionic-team/stencil-sass#12]
Hi guys,

I've build a component library with Stencil and now trying to use it in a stencil-app.

In the stencil-app if I add stencil-sass support and run `npm start` it attempts to compile my stencil component, and since i have the mixin.scss file in `injdectGlobalPaths` inside the component project, the stencil-app will fail to compile sass.

Repos:
Component:
https://github.com/seanwuapps/wu-components
StencilApp:
https://github.com/seanwuapps/wu-components-docs

**Comment by MrAntix** [comment]
looks like the compiled **collection-manifest.json** contains a ref to the scss file not the output of the sass build

```
    {
      "tag": "my-component",
      "dependencies": [],
      "componentClass": "MyComponent",
      "componentPath": "my-component/component.js",
      "styles": {
        "$": {
          "stylePaths": [
            "my-component/component.scss"
          ]
        }
      },
```

If I manually change .scss to .css all works as expected

Also, this is probably why I am not getting styles in my e2e tests

@adamdbradley is this something that should be fixed in this project or in the stencil compiler?
