### ISSUE TITLE
Stencil-sass v2

### ISSUE THREAD

**Issue by xBau** [ionic-team/stencil-sass#52]
After making a clean install it is still downloading v1.4.1 so I can't use latest features from Sass like @use.
Docs says that there are a version 2, so that seems to be the issue. Am I doing something wrong?

Thanks in advance :)

<img width="264" alt="Screenshot 2021-04-20 at 13 02 05" src="https://user-images.githubusercontent.com/2278988/115386148-53c00380-a1d9-11eb-81cd-e48e81f930aa.png">

<img width="852" alt="Screenshot 2021-04-16 at 14 06 20" src="https://user-images.githubusercontent.com/2278988/115386192-5f132f00-a1d9-11eb-9ebb-0e9d2f906e47.png">

**Comment by xBau** [comment]
For anyone with the same issue, this did the trick for me:
```
npm install @stencil/sass@2.0.0-0 --save-dev
```

PS: Dart sass was released more than 2 years ago, so it should be the default imho.

**Comment by tfrijsewijk** [comment]
Version `2.0.0-0` is published with dist-tag `next` instead of `latest` (which is still 1.4.1).

You can also install version `2.0.0-0` using `npm install @stencil/sass@next`.

Regarding your comment about Dart sass being default: `@stencil/sass` 1.x already uses dart-sass, but there was an issue using `injectGlobalPaths`. You can read more about that here: https://www.npmjs.com/package/@stencil/sass/v/2.0.0-0#user-content-inject-globals-sass-paths
