### ISSUE TITLE
Make `sass` a peerDependency

### ISSUE THREAD

**Issue by Richienb** [ionic-team/stencil-sass#61]
Instead of manually updating the sass dependency every time an update is available, it could be done by the consumer instead.

**Comment by tgrassl** [comment]
This would be really helpful for us as well 👍

**Comment by sommereder** [comment]
+100

**Comment by rwaskiewicz** [comment]
Hey folks,

Thanks for the patience on this one. After doing a little digging and discussing with the team, we've come to consensus that making `sass` a peer dependency is not something we feel is the right decision for this library.

This decision is influenced by the following points:

- We believe that making `sass` a peer dependency will increase the difficulty in maintaining this library. The points below can lead to incompatibilities between this library and `sass` (increasing maintenance burden):
  - `sass` can have breaking changes in minor versions, often called "maybe breaking changes" ([reference](https://sass-lang.com/documentation/breaking-changes))
  - The Sass 1.55 upgrade breaks the development cycle of `@stencil/sass`, as typings provided by `Sass` change in ways that cause build failures
- We control the version of `sass` used today, which simplifies our support matrix of this library and `sass`
- While we could make `sass` a peer-dependency, we believe we would need to make that peer-dependency rather restrictive, which we believe creates a compromise where nobody is quite pleased with the outcome.

I'm going to be scheduling https://github.com/ionic-team/stencil-sass/pull/157 to be completed in the near future, so that we can support a newer version of Sass.

Thanks!
