### ISSUE TITLE
Wrong transpilation of host element

### ISSUE THREAD

**Issue by Sebosek** [ionic-team/stencil-sass#9]
Hi,

```
:host([disabled]) {
    pointer-events: none;
    color: $color__gray--dark;
}
```

is wrongly transpilet to

```
:host {
  pointer-events: none;
  color: #D6D6D6; }
```
-- missing `disabled` attribute.

**Comment by jaredcbaum** [comment]
You could do:
`:host(.disabled) {
    pointer-events: none;
    color: $color__gray--dark;
}`
if you wanted to style when the disabled class is applied.

Since the Host element itself won't be an item that can accept focus or input (for example a textbox or button), you wouldn't be able to style with the :disabled css selector anyway.
In your case you could do:
`button:disabled {
    pointer-events: none;
    color: $color__gray--dark;
}`

**Comment by stevenpetryk** [comment]
That's just a workaround, though. Regardless of the ability to work around it, the compiler still has incorrect output.
